{"uuid": "53d6c2d5-fbe3-469b-ba1d-0b776677d8aa", "children": ["f8b736b2-d32a-459a-b990-09691687fb90"], "befores": [{"name": "_xunit_setup_class_fixture_TestHappyPath", "status": "broken", "statusDetails": {"message": "configparser.NoSectionError: No section: 'Auth'\n", "trace": "  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\Users\\dwilson3\\Documents\\Python-Automation-Scripts\\MainFolder\\BaseFolder\\Baseclass.py\", line 13, in setup_class\n    cls.fuse = fuseAuth(config)\n               ~~~~~~~~^^^^^^^^\n  File \"C:\\Users\\dwilson3\\Documents\\Python-Automation-Scripts\\MainFolder\\Auth\\Auth.py\", line 15, in __init__\n    self.Fuse_ClientID = config.get(\"Auth\", \"Fuse_ClientID\")\n                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\configparser.py\", line 812, in get\n    d = self._unify_values(section, vars)\n  File \"C:\\Users\\dwilson3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\configparser.py\", line 1186, in _unify_values\n    raise NoSectionError(section) from None\n"}, "start": 1760333607331, "stop": 1760333607333}], "start": 1760333607331, "stop": 1760333607686}